version: "3.7"
services:
  app:
    image: openregistry/open-registry:0.1.6
    command: lein run
    environment:
      - PORT=5432
      - METRICS_PORT=2345
      - SERVER_THREADS=16
      - IPFS_API=/ip4/ipfs/tcp/5001
      - REGISTRY_URL=https://npm.open-registry.dev
      - SERVER_DEV=false
      - UPDATE_ON_BOOT=true
    restart: always
  metrics:
    volumes:
      - prometheus:/prometheus
      - ./infra/prometheus-production.yml:/prometheus.yml
    restart: always
  ipfs:
    restart: always
    command: daemon --migrate=true
  front:
    ports:
      - 80:80
      - 443:443
      - 9180:9180
    volumes:
      - ./infra/caddy/Caddyfile.production:/etc/Caddyfile
      - caddy:/root/.caddy
    restart: always
  dashboard:
    volumes:
      - ./infra/grafana/config-production.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
      - ./infra/grafana/:/etc/grafana/provisioning
    restart: always
  finance:
    restart: always
