{
 "title": "General",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "caddy_http_request_count_total", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "HTTP Request Durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{host=\"npm.open-registry.dev\"}[10m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_metadata_cached", "legendFormat": "Serve from cache" },
    { "expr": "app_metadata_fetch_npm", "legendFormat": "Fetch from npm" }
   ]
  },
  {
   "title": "Tarballs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_tarball_cached", "legendFormat": "Serve from cache" },
    { "expr": "app_tarball_fetch_npm", "legendFormat": "Fetch from npm" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "caddy_http_request_count_total", "legendFormat": "{{ host }}" }
   ]
  }
 ]
}