{
 "title": "General",
 "time": { "from": "2019-05-08T11:19:04.512Z", "to": "2019-05-08T11:22:23.243Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "content": "![](https://open-registry.dev/logo.png)",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "content": "\n# Open-Registry Dashboard\n\nWelcome to the Open-Registry Dashboard. Here you can find all the public information about the running infrastructure. If you have any questions, please open a issue in the [GitHub repository for Open-Registry](https://github.com/open-services/open-registry)\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Balance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    { "expr": "open_registry_balance / 100" }
   ]
  },
  {
   "title": "Yearly Income",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "open_registry_yearly_income / 100"
    }
   ]
  },
  {
   "title": "Backers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "open_registry_backers_count" }
   ]
  },
  { "title": "Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Metadata (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(app_metadata_cached[1m])", "legendFormat": "Serve from cache" },
    {
     "expr": "rate(app_metadata_fetch_npm[1m])",
     "legendFormat": "Fetch from npm"
    }
   ]
  },
  {
   "title": "Tarballs (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(app_tarball_cached[1m])", "legendFormat": "Serve from cache" },
    {
     "expr": "rate(app_tarball_fetch_npm[1m])",
     "legendFormat": "Fetch from npm"
    }
   ]
  },
  {
   "title": "Updates received from npm reigistry (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(app_change_feed_skip[1m])", "legendFormat": "Skipped update" },
    {
     "expr": "rate(app_change_feed_update[1m])",
     "legendFormat": "Updated metadata"
    }
   ]
  },
  {
   "title": "Uptime Monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Up" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{ job}}" }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total HTTP Requests (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(caddy_http_request_count_total[1m])",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "HTTP Request Durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket[10m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "caddy_http_request_count_total", "legendFormat": "{{ host }}/{{proto}}" }
   ]
  },
  { "title": "IPFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ipfs_p2p_peers_total)", "legendFormat": "Connected Peers" }
   ]
  },
  {
   "title": "Peers by Transport",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "ipfs_p2p_peers_total", "legendFormat": "{{transport}}" }
   ]
  }
 ]
}